"""create artifact table

Revision ID: 0d1e8497e173
Revises:
Create Date: 2025-10-23 07:59:41.290876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1e8497e173'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('model3d_url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(length=1000), nullable=True),
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('title', name=op.f('uq_artifacts_title'))
    )
    op.create_index('ix_artifacts_title', 'artifacts', ['title'], unique=False, postgresql_ops={'title': 'text_pattern_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artifacts_title', table_name='artifacts', postgresql_ops={'title': 'text_pattern_ops'})
    op.drop_table('artifacts')
    # ### end Alembic commands ###
